/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.vmaudev.course_service.event;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CourseDeleteEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1099321334885781533L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CourseDeleteEvent\",\"namespace\":\"com.vmaudev.course_service.event\",\"fields\":[{\"name\":\"courseId\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CourseDeleteEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CourseDeleteEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CourseDeleteEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CourseDeleteEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CourseDeleteEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CourseDeleteEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CourseDeleteEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CourseDeleteEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CourseDeleteEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence courseId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CourseDeleteEvent() {}

  /**
   * All-args constructor.
   * @param courseId The new value for courseId
   */
  public CourseDeleteEvent(java.lang.CharSequence courseId) {
    this.courseId = courseId;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return courseId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: courseId = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'courseId' field.
   * @return The value of the 'courseId' field.
   */
  public java.lang.CharSequence getCourseId() {
    return courseId;
  }


  /**
   * Sets the value of the 'courseId' field.
   * @param value the value to set.
   */
  public void setCourseId(java.lang.CharSequence value) {
    this.courseId = value;
  }

  /**
   * Creates a new CourseDeleteEvent RecordBuilder.
   * @return A new CourseDeleteEvent RecordBuilder
   */
  public static com.vmaudev.course_service.event.CourseDeleteEvent.Builder newBuilder() {
    return new com.vmaudev.course_service.event.CourseDeleteEvent.Builder();
  }

  /**
   * Creates a new CourseDeleteEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CourseDeleteEvent RecordBuilder
   */
  public static com.vmaudev.course_service.event.CourseDeleteEvent.Builder newBuilder(com.vmaudev.course_service.event.CourseDeleteEvent.Builder other) {
    if (other == null) {
      return new com.vmaudev.course_service.event.CourseDeleteEvent.Builder();
    } else {
      return new com.vmaudev.course_service.event.CourseDeleteEvent.Builder(other);
    }
  }

  /**
   * Creates a new CourseDeleteEvent RecordBuilder by copying an existing CourseDeleteEvent instance.
   * @param other The existing instance to copy.
   * @return A new CourseDeleteEvent RecordBuilder
   */
  public static com.vmaudev.course_service.event.CourseDeleteEvent.Builder newBuilder(com.vmaudev.course_service.event.CourseDeleteEvent other) {
    if (other == null) {
      return new com.vmaudev.course_service.event.CourseDeleteEvent.Builder();
    } else {
      return new com.vmaudev.course_service.event.CourseDeleteEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for CourseDeleteEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CourseDeleteEvent>
    implements org.apache.avro.data.RecordBuilder<CourseDeleteEvent> {

    private java.lang.CharSequence courseId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.vmaudev.course_service.event.CourseDeleteEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.courseId)) {
        this.courseId = data().deepCopy(fields()[0].schema(), other.courseId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing CourseDeleteEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.vmaudev.course_service.event.CourseDeleteEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.courseId)) {
        this.courseId = data().deepCopy(fields()[0].schema(), other.courseId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'courseId' field.
      * @return The value.
      */
    public java.lang.CharSequence getCourseId() {
      return courseId;
    }


    /**
      * Sets the value of the 'courseId' field.
      * @param value The value of 'courseId'.
      * @return This builder.
      */
    public com.vmaudev.course_service.event.CourseDeleteEvent.Builder setCourseId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.courseId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'courseId' field has been set.
      * @return True if the 'courseId' field has been set, false otherwise.
      */
    public boolean hasCourseId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'courseId' field.
      * @return This builder.
      */
    public com.vmaudev.course_service.event.CourseDeleteEvent.Builder clearCourseId() {
      courseId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CourseDeleteEvent build() {
      try {
        CourseDeleteEvent record = new CourseDeleteEvent();
        record.courseId = fieldSetFlags()[0] ? this.courseId : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CourseDeleteEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<CourseDeleteEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CourseDeleteEvent>
    READER$ = (org.apache.avro.io.DatumReader<CourseDeleteEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.courseId);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.courseId = in.readString(this.courseId instanceof Utf8 ? (Utf8)this.courseId : null);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.courseId = in.readString(this.courseId instanceof Utf8 ? (Utf8)this.courseId : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










